apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: vaccination-progress

build:
  artifacts:
    - image: semba/vaccination-progress
      context: web-app

    - image: semba/vaccination-progress-spark
      context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
