#Begin: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-progress
  labels:
    app: vaccination-progress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccination-progress-web
  template:
    metadata:
      labels:
        app: vaccination-progress-web
    spec:
      containers:
        - name: vaccination-progress-web
          image: semba/vaccination-progress
          ports:
            - containerPort: 3000

---
#Begin: Service
kind: Service
apiVersion: v1
metadata:
  name: vaccination-progress-service
spec:
  selector:
    app: vaccination-progress-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
#End: Service

---
#Begin: Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaccination-progress-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaccination-progress-service
                port:
                  number: 3000
